[package]
name = "toms-data-onion-rust"
version = "0.1.0"
authors = ["Dexter Darwich"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.41"
ascii85 = "0.2.1"